language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  matrix:
    - UPGRADE=7.x-1.x-dev
  global:
    secure: Jc9tSi/yf5qy1Bz0NipXxixXFYMgksorzHReDLGoeSRGG/5aCO2Py1/SQko6Y6YzR0fvuByWXFM8T8Ob0+soeC26CnLygARm50h4Px5vv9iW0RUd0jkmMqMz67fIrAOptfp1lbHe2m9Xe91XhBDTcF6HhdXXKc71y5WsRAawoPA=

matrix:
  fast_finish: true

install:
  # Add the Google Chrome packages.
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update > /dev/null

  # Create a database for our Drupal site.
  - "mysql -e 'create database drupal;'"

  # Install the latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --prefer-source --no-interaction drush/drush:6.*
  - drush dl -y drupalorg_drush-7.x-1.x-dev --destination=$HOME/.drush
  - drush cc drush

  # Build Codebase
  - cd ../
  - mkdir profiles
  - mv hotsauce profiles/
  - mkdir drupal
  - mv profiles drupal/

  # Build the current branch.
  - cd drupal
  - drush make --yes profiles/hotsauce/drupal-org-core.make --prepare-install
  - drush make --yes profiles/hotsauce/drupal-org.make --no-core --contrib-destination=profiles/hotsauce
  - drush dl diff
  - mkdir sites/default/private
  - mkdir sites/default/private/files
  - mkdir sites/default/private/temp
  - cd ../

  # Verify that all the .make files will work on Drupal.org.
  - drush verify-makefile drupal/profiles/hotsauce/drupal-org.make
  - find drupal/profiles/hotsauce/modules -name \*.make -print0 | xargs -0 -n1 drush verify-makefile

  # Download an old version to test upgrading from.
  - if [[ "$UPGRADE" != none ]]; then drush dl hotsauce-$UPGRADE; fi

  # Setup files
  - sudo chmod -R 777 drupal/sites/all

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Chrome and ChromeDriver
  - sudo apt-get install google-chrome-stable
  - wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
  - unzip -a chromedriver_linux64.zip

  # Insane hack from jsdevel:
  # https://github.com/jsdevel/travis-debugging/blob/master/shim.bash
  # This allows chrome-sandbox to work in side of OpenVZ, because I can't
  # figure out how to start chrome with --no-sandbox.
  - export CHROME_SANDBOX=/opt/google/chrome/chrome-sandbox
  - sudo rm -f $CHROME_SANDBOX
  - sudo wget https://googledrive.com/host/0B5VlNZ_Rvdw6NTJoZDBSVy1ZdkE -O $CHROME_SANDBOX
  - sudo chown root:root $CHROME_SANDBOX; sudo chmod 4755 $CHROME_SANDBOX
  - sudo md5sum $CHROME_SANDBOX

  # Get Selenium
  - wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar
  - java -jar selenium-server-standalone-2.41.0.jar -Dwebdriver.chrome.driver=`pwd`/chromedriver > /dev/null 2>&1 &
  - sleep 5

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  # Configure GIT
  - git config --global user.email "travis@kalamuna.com"
  - git config --global user.name "Travis-CI"

  # Expand max_nesting_level to prevent error
  - phpenv config-add drupal/profiles/hotsauce/travis.php.ini

  # Do the site install
  - cd drupal
  - drush si hotsauce --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="hotsauce" --yes
  - drush dis -y dblog
  - drush vset -y file_private_path "sites/default/private/files"
  - drush vset -y file_temporary_path "sites/default/private/temp"
  - cd ../drupal
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - SERVER_PID=$!
  - sleep 3

script:
  # Just don't run the default PhpUnit tests
  - cat /dev/null

after_script:

  # Stop the webserver so that it's not still running when MySQL is stopped.
  - kill $SERVER_PID

after_success:
  - cd ..
  - git clone https://github.com/kala-travis/hotsauce-drops-7.git hotdrops
  - cp -fR drupal/* hotdrops
  - cd hotdrops
  - git config --global credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add --all
  - git commit -m "Successful build"
  - git push

notifications:
  email:
    recipients:
      - hotsauce-ci@googlegroups.com
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#hotsauce"
    on_success: always
    on_failure: always
